package consumer

const (
	ORDER_STATUS_RECEIVED = 1
	ORDER_STATUS_PUBLISHED = 2
	ORDER_STATUS_BOOKED = 3
	ORDER_STATUS_CANCELED = 4
	ORDER_STATUS_OTW = 5
	ORDER_STATUS_STARTED = 6     
	ORDER_STATUS_FINISHED = 7

	PAYMENT_METHOD_CASH = 1
	PAYMENT_METOHD_CREDIT_CARD = 2
	PAYMENT_METHOD_GO_PAY = 3
	PAYMENT_METHOD_GOJEK_KREDIT = 4
	
	GO_GLAM_VERTICAL_ID = 1
	GO_MASSAGE_VERTICAL_ID = 2
	GO_CLEAN_VERTICAL_ID = 3
	GO_AUTO_VERTICAL_ID = 4
	
	BLAST_TYPE_ADD_ORDER = 1
	BLAST_TYPE_CANCEL_ORDER  = 2
)
